pipeline {
    agent any
    environment {
        COMPOSE_FILE = 'docker-compose.yml'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/erwin-suyatno/library-managment'
            }
        }
        stage('Build and Deploy') {
            steps {
                sh 'docker-compose up -d --build'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker ps'
            }
        }
    }
}
